use super::disabled::Disabled;

/// Available GPIO pads.
pub struct Pads<GLB> {
    /// GPIO I/O 0.
    pub io0: Disabled<GLB, 0>,
    /// GPIO I/O 1.
    pub io1: Disabled<GLB, 1>,
    /// GPIO I/O 2.
    pub io2: Disabled<GLB, 2>,
    /// GPIO I/O 3.
    pub io3: Disabled<GLB, 3>,
    /// GPIO I/O 4.
    pub io4: Disabled<GLB, 4>,
    /// GPIO I/O 5.
    pub io5: Disabled<GLB, 5>,
    /// GPIO I/O 6.
    pub io6: Disabled<GLB, 6>,
    /// GPIO I/O 7.
    pub io7: Disabled<GLB, 7>,
    /// GPIO I/O 8.
    pub io8: Disabled<GLB, 8>,
    /// GPIO I/O 9.
    pub io9: Disabled<GLB, 9>,
    /// GPIO I/O 10.
    pub io10: Disabled<GLB, 10>,
    /// GPIO I/O 11.
    pub io11: Disabled<GLB, 11>,
    /// GPIO I/O 12.
    pub io12: Disabled<GLB, 12>,
    /// GPIO I/O 13.
    pub io13: Disabled<GLB, 13>,
    /// GPIO I/O 14.
    pub io14: Disabled<GLB, 14>,
    /// GPIO I/O 15.
    pub io15: Disabled<GLB, 15>,
    /// GPIO I/O 16.
    pub io16: Disabled<GLB, 16>,
    /// GPIO I/O 17.
    pub io17: Disabled<GLB, 17>,
    /// GPIO I/O 18.
    pub io18: Disabled<GLB, 18>,
    /// GPIO I/O 19.
    pub io19: Disabled<GLB, 19>,
    /// GPIO I/O 20.
    pub io20: Disabled<GLB, 20>,
    /// GPIO I/O 21.
    pub io21: Disabled<GLB, 21>,
    /// GPIO I/O 22.
    pub io22: Disabled<GLB, 22>,
    /// GPIO I/O 23.
    pub io23: Disabled<GLB, 23>,
    /// GPIO I/O 24.
    pub io24: Disabled<GLB, 24>,
    /// GPIO I/O 25.
    pub io25: Disabled<GLB, 25>,
    /// GPIO I/O 26.
    pub io26: Disabled<GLB, 26>,
    /// GPIO I/O 27.
    pub io27: Disabled<GLB, 27>,
    /// GPIO I/O 28.
    pub io28: Disabled<GLB, 28>,
    /// GPIO I/O 29.
    pub io29: Disabled<GLB, 29>,
    /// GPIO I/O 30.
    pub io30: Disabled<GLB, 30>,
    /// GPIO I/O 31.
    pub io31: Disabled<GLB, 31>,
    /// GPIO I/O 32.
    pub io32: Disabled<GLB, 32>,
    /// GPIO I/O 33.
    pub io33: Disabled<GLB, 33>,
    /// GPIO I/O 34.
    pub io34: Disabled<GLB, 34>,
    /// GPIO I/O 35.
    pub io35: Disabled<GLB, 35>,
    /// GPIO I/O 36.
    pub io36: Disabled<GLB, 36>,
    /// GPIO I/O 37.
    pub io37: Disabled<GLB, 37>,
    /// GPIO I/O 38.
    pub io38: Disabled<GLB, 38>,
    /// GPIO I/O 39.
    pub io39: Disabled<GLB, 39>,
    /// GPIO I/O 40.
    pub io40: Disabled<GLB, 40>,
    /// GPIO I/O 41.
    pub io41: Disabled<GLB, 41>,
    /// GPIO I/O 42.
    pub io42: Disabled<GLB, 42>,
    /// GPIO I/O 43.
    pub io43: Disabled<GLB, 43>,
    /// GPIO I/O 44.
    pub io44: Disabled<GLB, 44>,
    /// GPIO I/O 45.
    pub io45: Disabled<GLB, 45>,
}
