//! BL616/BL618 single-core Wi-Fi 6, Bluetooth 5.3, Zigbee AIoT system-on-chip.

mod image_header;
mod peripheral;
pub use image_header::*;
pub use peripheral::*;

#[cfg(all(feature = "bl616", target_arch = "riscv32"))]
#[unsafe(naked)]
#[unsafe(link_section = ".text.entry")]
#[unsafe(export_name = "_start")]
unsafe extern "C" fn start() -> ! {
    use crate::arch::rvi::Stack;
    const LEN_STACK: usize = 1 * 1024;
    #[unsafe(link_section = ".bss.uninit")]
    static mut STACK: Stack<LEN_STACK> = Stack([0; LEN_STACK]);
    core::arch::naked_asm!(
        "   la      sp, {stack}
        li      t0, {hart_stack_size}
        add     sp, sp, t0",
        "   la      t1, sbss
        la      t2, ebss
    1:  bgeu    t1, t2, 1f
        sw      zero, 0(t1)
        addi    t1, t1, 4
        j       1b
    1:",
        "   la      t3, sidata
        la      t4, sdata
        la      t5, edata
    1:  bgeu    t4, t5, 1f
        lw      t6, 0(t3)
        sw      t6, 0(t4)
        addi    t3, t3, 4
        addi    t4, t4, 4
        j       1b
    1:",
        "   call  {main}",
        stack = sym STACK,
        hart_stack_size = const LEN_STACK,
        main = sym main,
    )
}

#[cfg(all(feature = "bl616", target_arch = "riscv32"))]
unsafe extern "Rust" {
    // This symbol is generated by `#[entry]` macro
    fn main() -> !;
}

// Used by macros only.
#[allow(unused)]
#[doc(hidden)]
#[inline(always)]
pub fn __rom_init_params(xtal_hz: u32) -> (Peripherals, Clocks) {
    (Peripherals::__new(), Clocks::__new(xtal_hz))
}
